// Generated by https://quicktype.io

export interface TopLevel {
    id?:     any;
    titulo?: string;
    cuerpo?: string;
    fecha?:  Date;
    id_usuario?: number;
}



export interface User {
    id: string;
    usuario:    string;
    correo:     string;
    contrasena: string;
}

export interface Task {
    id?:     number;
    titulo?: string;
    fecha?:  Date;
    estado?: number;
    id_usuario?: number;
}

// Estructura para la tabla de tokens
export interface Token {
    id_token?: number;
    correo_electronico: string;
    token: string;
    estatus: 'abierta' | 'cerrada';
    fecha_creacion: string;
}