// Generated by https://quicktype.io

export interface TopLevel {
    id?:     any;
    titulo?: string;
    cuerpo?: string;
    fecha?:  Date;
    id_usuario?: number;
}


export interface User {
    id: string;
    usuario:    string;
    correo:     string;
    contrasena: string;
}
