// Generated by https://quicktype.io

export interface TopLevel {
    id?:     number;
    titulo?: string;
    cuerpo?: string;
    fecha?:  Date;
}

export interface Usuario {
    id_usuario?: number;
    nombre: string;
    nombre_usuario: string;
    correo_electronico: string;
    contrasena: string;
    rol: string;
    estado_cuenta: 'activo' | 'inactivo' | 'suspendido';
    fecha_creacion: string;
    ultimo_acceso: string ;
    telefono: string ;
    direccion: string ;
    ciudad: string ;
    estado_provincia: string ;
    pais: string ;
    codigo_postal: string ;
}

export interface Task {
    id?:     number;
    titulo?: string;
    fecha?:  Date;
    estado?: number;
}

// Estructura para la tabla de tokens
export interface Token {
    id_token?: number;
    correo_electronico: string;
    token: string;
    estatus: 'abierta' | 'cerrada';
    fecha_creacion: string;
}